<?php
/** @var \ParadoxLabs\TokenBase\Block\Form\Cc $block */
// @codingStandardsIgnoreFile
// TODO: Lots fixup, JS actions, validation changes, blah blah blah blah
?>
<?php $_code = $block->getMethodCode() ?>
<fieldset class="fieldset payment items ccard <?php echo $_code ?>" id="payment_form_<?php echo $_code ?>" style="display: none;">
    <?php if ($block->getMethod()->getConfigData('show_branding')): ?>
        <div class="field">
            <img src="<?php echo $block->getViewFileUrl($block->getBrandingImage()); ?>" alt="<?php echo $block->getMethod()->getConfigData('title'); ?>" />
        </div>
    <?php endif; ?>
    <?php if ($block->haveStoredCards()): ?>
        <div class="field">
            <label for="<?php echo $_code; ?>_card_id" class="label"><?php echo __('Pay with credit card on file'); ?></label>
            <div class="control">
                <select name="payment[card_id]" id="<?php echo $_code; ?>_card_id" data-validate='{required:true}' class="select">
                    <option value=""><?php echo __('-- Select One --'); ?></option>
                    <?php foreach ($block->getStoredCards() as $card): ?>
                        <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
                        <?php $card = $card->getTypeInstance(); ?>
                        <option value="<?php echo $card->getHash(); ?>" <?php if ($card->getId() == $block->getInfoData('tokenbase_id') || count($block->getStoredCards()) == 1): ?>selected="selected"<?php endif; ?>><?php echo $card->getLabel(); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <?php if ($block->getMethod()->getConfigData('require_ccv')): ?>
            <div class="field">
                <div class="control">
                    <label for="<?php echo $_code; ?>_saved_cc_cid" class="left"><?php echo __('Card Code'); ?></label>&nbsp;
                    <input type="text" title="<?php echo __('Card Verification Number') ?>" class="input-text <?php echo $_code; ?>_require required-entry validate-digits-range digits-range-001-9999" id="<?php echo $block->getMethodCode(); ?>_saved_cc_cid" name="payment[saved_cc_cid]" autocomplete="off" value="" style="width:4em;" maxlength="4" />
                    <div class="note">
                        <a href="#" class="action cvv" title="<?php echo __('What is this?') ?>" data-mage-init='{"tooltip": {"content": "<?php echo $_content ?>"}}'><span><?php echo __('What is this?') ?></span></a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="field">
            <div class="control">
                <?php echo __('Or,'); ?> <a href="#" id="<?php echo $_code; ?>_add_new"><?php echo __('use a different card.'); ?></a>
            </div>
        </div>
    <?php endif; ?>
    <div class="field type required">
        <label for="<?php echo $_code ?>_cc_type" class="label"><span><?php echo __('Credit Card Type') ?></span></label>
        <div class="control">
            <select id="<?php echo $_code ?>_cc_type"
                    data-mage-init='{"creditCardType":{"creditCardTypeContainer":"#<?php echo $_code ?>_cc_type_ss_div"}}'
                    name="payment[cc_type]" data-validate='{required:true, "validate-cc-type-select":"#<?php echo $_code ?>_cc_number"}' class="select">
                <option value=""><?php echo __('--Please Select--')?></option>
                <?php $_ccType = $block->getInfoData('cc_type') ?>
                <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field number required">
        <label for="<?php echo $_code ?>_cc_number" class="label"><span><?php echo __('Credit Card Number') ?></span></label>
        <div class="control">
            <input type="number" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo __('Credit Card Number') ?>" class="input-text" value="" data-validate='{"required-number":true, "validate-cc-number":"#<?php echo $_code ?>_cc_type", "validate-cc-type":"#<?php echo $_code ?>_cc_type"}'/>
        </div>
    </div>
    <div class="field date required" id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="label"><span><?php echo __('Expiration Date') ?></span></label>
        <div class="control">
            <div class="fields group group-2">
                <div class="field no-label month">
                    <div class="control">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="select month" data-validate='{required:true, "validate-cc-exp":"#<?php echo $_code ?>_expiration_yr"}'>
                            <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
                            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
                <div class="field no-label year">
                    <div class="control">
                        <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="select year" data-validate='{required:true}'>
                            <?php foreach ($block->getCcYears() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
        <div class="field cvv required" id="<?php echo $_code ?>_cc_type_cvv_div">
            <label for="<?php echo $_code ?>_cc_cid" class="label"><span><?php echo __('Card Verification Number') ?></span></label>
            <div class="control">
                <input type="number" title="<?php echo __('Card Verification Number') ?>" class="input-text cvv" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" data-validate='{"required-number":true, "validate-cc-cvn":"#<?php echo $_code ?>_cc_type"}' />
                <?php $_content = '<img src=\"' . $block->getViewFileUrl('Magento_Checkout::cvv.png') . '\" alt=\"' . __('Card Verification Number Visual Reference') . '\" title=\"' . __('Card Verification Number Visual Reference') . '\" />'; ?>
                <div class="note">
                    <a href="#" class="action cvv" title="<?php echo __('What is this?') ?>" data-mage-init='{"tooltip": {"content": "<?php echo $_content ?>"}}'><span><?php echo __('What is this?') ?></span></a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->hasSsCardType()): ?>
        <div class="field switch solo required" id="<?php echo $_code ?>_cc_type_ss_div">
            <div class="nested">
                <div class="field switch solo required">
                    <label for="<?php echo $_code ?>_cc_issue" class="label"><span><?php echo __('Switch/Solo/Maestro Only') ?></span></label>
                </div>
                <div class="field number required">
                    <label for="<?php echo $_code ?>_cc_issue" class="label"><span><?php echo __('Issue Number') ?></span></label>
                    <div class="control">
                        <input type="text" title="<?php echo __('Issue Number') ?>" class="input-text cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" data-validate='{"validate-cc-ukss":true}'/>
                    </div>
                </div>

                <div class="field date required">
                    <label for="<?php echo $_code ?>_start_month" class="label"><span><?php echo __('Start Date') ?></span></label>
                    <div class="control">
                        <div class="fields group group-2">
                            <div class="field no-label">
                                <div class="control">
                                    <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="select month" data-validate='{"validate-cc-ukss":true}'>
                                        <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $block->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                            <div class="field no-label">
                                <div class="control">
                                    <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="select year" data-validate='{"validate-cc-ukss":true}'>
                                        <?php foreach ($block->getSsStartYears() as $k => $v): ?>
                                            <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $block->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                        <?php endforeach ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="adv container" data-validation-msg="validate-cc-ukss">&nbsp;</div>
            </div>
        </div>
    <?php endif; ?>
    <?php echo $block->getChildHtml() ?>
    <?php if (!$block->isGuestCheckout() && $block->getMethod()->getConfigData('allow_unsaved')): ?>
        <div class="field">
            <label>&nbsp;</label>
            <input type="hidden" name="payment[save]" value="0" />
            <input type="checkbox" name="payment[save]" id="<?php echo $block->getMethodCode(); ?>_save" value="1" checked="checked" autocomplete="on" />
            <label for="<?php echo $block->getMethodCode(); ?>_save" style="float:none;font-weight:normal;"><?php echo __('Save for next time'); ?></label>
        </div>
    <?php elseif (!$block->isGuestCheckout()): ?>
        <div class="field">
            <?php echo __('<strong>Note:</strong> For your convenience, this data will be stored securely by our payment processor.'); ?>
        </div>
    <?php endif; ?>
</fieldset>
