<?php
/** @var \ParadoxLabs\TokenBase\Block\Customer\Form $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $code = $escaper->escapeHtmlAttr($block->getCode()); ?>

<div class="block-title">
    <h2>
        <?php if ($block->isEdit()): ?>
            <?= $escaper->escapeHtml(__('Editing %1', $block->getCard()->getLabel())) ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('Add A Bank Account (eCheck)')) ?>
        <?php endif; ?>
    </h2>
</div>

<form action="<?= $escaper->escapeHtmlAttr($block->getAction()) ?>" method="post" id="form-validate" class="checkout-payment-method" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="id" value="<?= $block->getCard()->getId() ? $escaper->escapeHtmlAttr($block->getCard()->getHash()) : '' ?>" />
    <input type="hidden" name="method" value="<?= /* @noEscape */ $code ?>" />
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Cardholder Information')) ?></span></legend><br>

        <?= /* @noEscape */ $block->getNameBlockHtml() ?>
        <div class="field company">
            <label class="label" for="company"><span><?= $escaper->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[company]" id="company" title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
            </div>
        </div>
        <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
        <div class="field telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> required<?php endif; ?>">
            <label class="label" for="telephone"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[telephone]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($phoneValidation) ?>" id="telephone">
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Cardholder Address')) ?></span></legend><br>

        <?php $_streetValidationClass = $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
        <div class="field street required">
            <label for="street" class="label"><span><?= $escaper->escapeHtml(__('Street')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address')) ?>" id="street" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                        <?php $lineNo = (int)($_i+1); ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $lineNo ?>">
                                <span><?= $escaper->escapeHtml(__('Street Address %1', $lineNo)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="street_<?= /* @noEscape */ $lineNo ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= $escaper->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[city]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $escaper->escapeHtmlAttr(__('City')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region-id"><span><?= $escaper->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select id="region-id" name="billing[region_id]" title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" <?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="billing[region]" value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= $escaper->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="control">
                <input type="text" name="billing[postcode]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= $escaper->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= /* @noEscape */ $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]') ?>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset payment items ccard <?= /* @noEscape */ $code ?>">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Bank Information')) ?></span></legend><br>

        <div class="field name required hide-if-card-selected">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-name" class="label"><span><?= $escaper->escapeHtml(__('Name on Account')) ?></span></label>
            <div class="control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-account-name" name="payment[echeck_account_name]"
                       title="<?= $escaper->escapeHtmlAttr(__('Name on Account')) ?>" class="input-text" maxlength="22"
                       value="<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_account_name')) ?>"
                       data-validate='{required:true}' />
            </div>
        </div>
        <div class="field name required hide-if-card-selected">
            <label for="<?= /* @noEscape */ $code ?>-echeck-bank-name" class="label"><span><?= $escaper->escapeHtml(__('Bank Name')) ?></span></label>
            <div class="control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-bank-name" name="payment[echeck_bank_name]"
                       title="<?= $escaper->escapeHtmlAttr(__('Bank Name')) ?>" class="input-text" maxlength="50" autocomplete="off"
                       value="<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_bank_name')) ?>"
                       data-validate='{required:true}' />
            </div>
        </div>
        <div class="field number required hide-if-card-selected">
            <label for="<?= /* @noEscape */ $code ?>-echeck-routing-number" class="label"><span><?= $escaper->escapeHtml(__('Routing Number')) ?></span></label>
            <div class="control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-routing-number" name="payment[echeck_routing_no]"
                       title="<?= $escaper->escapeHtmlAttr(__('Routing Number')) ?>" class="input-text minimum-length-9" maxlength="9"
                       value="<?php if ($block->getCard()->getId() && $block->getCard()->getAdditional('echeck_routing_number_last4') != ''): ?>XXXX<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_routing_number_last4')) ?><?php endif; ?>" autocomplete="off"
                       data-validate='{"required-number":true,"validate-length":true}' />
            </div>
        </div>
        <div class="field number required hide-if-card-selected">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-number" class="label"><span><?= $escaper->escapeHtml(__('Account Number')) ?></span></label>
            <div class="control _with-tooltip">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-account-number" name="payment[echeck_account_no]"
                       title="<?= $escaper->escapeHtmlAttr(__('Account Number')) ?>" class="input-text minimum-length-5 maximum-length-17"
                       value="<?php if ($block->getCard()->getId() && $block->getCard()->getAdditional('echeck_account_number_last4') != ''): ?>XXXX<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_account_number_last4')) ?><?php endif; ?>" maxlength="17"
                       data-validate='{"required-number":true,"validate-length":true}' autocomplete="off" />
                <div class="field-tooltip tooltip note toggle">
                    <span class="field-tooltip-action tooltip-toggle action-cvv" tabindex="0" data-toggle="dropdown">
                        <span><?= $escaper->escapeHtml(__('Where do I find these numbers?')) ?></span>
                    </span>
                    <div class="tooltip-content" data-target="dropdown" aria-hidden="true">
                        <p><?= $escaper->escapeHtml(__('On the bottom of your checks, you will see three groups of numbers. Usually the first one is your routing number, and the second is your account number.')) ?></p>
                        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('ParadoxLabs_TokenBase::images/ach.png')) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Visual reference for locating routing number and account number on a check')) ?>" />
                    </div>
                </div>
            </div>
        </div>
        <div class="field type required hide-if-card-selected">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-type-checking" class="label"><span><?= $escaper->escapeHtml(__('Account Type')) ?></span></label>
            <div class="control">
                <?php $typeValue = $block->getCard()->getAdditional('echeck_account_type') ?: 'checking'; ?>
                <?php foreach ($block->getHelper()->getAchAccountTypes() as $k => $v): ?>
                    <div>
                        <input type="radio" name="payment[echeck_account_type]"
                               id="<?= /* @noEscape */ $code ?>-echeck-account-type-<?= $escaper->escapeHtmlAttr($k) ?>"
                               value="<?= $escaper->escapeHtmlAttr($k) ?>" <?php if ($k == $typeValue): ?>checked="checked"<?php endif ?>
                               data-validate='{"validate-one-required-by-name":true}' />
                        <label for="<?= /* @noEscape */ $code ?>-echeck-account-type-<?= $escaper->escapeHtmlAttr($k) ?>"><?= $escaper->escapeHtml($v) ?></label>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"><span><?= $escaper->escapeHtml(__('Cancel')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?=($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region-id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
