<?php
/** @var \ParadoxLabs\TokenBase\Block\Customer\Form $block */
// @codingStandardsIgnoreFile
?>
<?php $code = $block->getCode(); ?>

<div class="block-title">
    <h2>
        <?php if ($block->isEdit()): ?>
            <?php echo __('Editing %1', $block->getCard()->getLabel()); ?>
        <?php else: ?>
            <?php echo __('Add A Credit Card'); ?>
        <?php endif; ?>
    </h2>
</div>

<form action="<?php echo $block->getAction(); ?>" method="post" id="form-validate" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <input type="hidden" name="id" value="<?php echo $block->getCard()->getHash(); ?>" />
    <input type="hidden" name="method" value="<?php echo $code; ?>" />
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Cardholder Information') ?></span></legend><br>

        <?php echo $block->getNameBlockHtml() ?>
        <div class="field company">
            <label class="label" for="company"><span><?php echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="billing[company]" id="company" title="<?php echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="billing[telephone]" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php echo __('Phone Number') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone">
            </div>
        </div>
<?php /* Just why?
        <div class="field fax">
            <label class="label" for="fax"><span><?php echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="billing[fax]" id="fax" title="<?php echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
            </div>
        </div> */ ?>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Cardholder Address') ?></span></legend><br>

        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?php echo __('Street') ?></span></label>
            <div class="control">
                <input type="text" name="billing[street][]" value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php echo __('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php echo $_i+1 ?>">
                                <span><?php echo __('Street Address %1', $_i+1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="billing[street][]" value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php echo __('Street Address %1', $_i+1) ?>" id="street_<?php echo $_i+1 ?>" class="input-text <?php echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?php echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="billing[city]" value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php echo __('City') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?php echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="billing[region_id]" title="<?php echo __('State/Province') ?>" class="validate-select" <?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?php echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="billing[region]" value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php echo __('State/Province') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="billing[postcode]" value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?php echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]') ?>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset payment items ccard <?php echo $code ?>" id="payment_form_<?php echo $code ?>">
        <legend class="legend"><span><?php echo __('Credit Card Information') ?></span></legend><br>

        <div class="field type required">
            <label for="<?php echo $code ?>_cc_type" class="label"><span><?php echo __('CC Type') ?></span></label>
            <div class="control">
                <select id="<?php echo $code ?>_cc_type"
                        data-mage-init='{"creditCardType":{"creditCardTypeContainer":"#<?php echo $code ?>_cc_type_ss_div"}}'
                        name="payment[cc_type]" data-validate='{required:true, "validate-cc-type-select":"#<?php echo $code ?>_cc_number"}' class="select">
                    <option value=""><?php echo __('--Please Select--')?></option>
                    <?php $_ccType = $block->getCard()->getAdditional('cc_type') ?>
                    <?php foreach ($block->getCcBlock()->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="field number required">
            <label for="<?php echo $code ?>_cc_number" class="label"><span><?php echo __('CC Number') ?></span></label>
            <div class="control">
                <input type="text" id="<?php echo $code ?>_cc_number" name="payment[cc_number]" title="<?php echo __('Credit Card Number') ?>" class="input-text" value="<?php echo $block->getCard()->getLabel(false); ?>" data-validate='{"required-number":true, "validate-cc-number":"#<?php echo $code ?>_cc_type", "validate-cc-type":"#<?php echo $code ?>_cc_type"}' autcomplete="off" />
            </div>
        </div>
        <div class="field date required" id="<?php echo $code ?>_cc_type_exp_div">
            <label for="<?php echo $code ?>_expiration" class="label"><span><?php echo __('Expiration') ?></span></label>
            <div class="control">
                <div class="fields group group-2">
                    <div class="field no-label month">
                        <div class="control">
                            <select id="<?php echo $code ?>_expiration" name="payment[cc_exp_month]" class="select month" data-validate='{required:true, "validate-cc-exp":"#<?php echo $code ?>_expiration_yr"}'>
                                <?php $_ccExpMonth = $block->getCard()->getAdditional('cc_exp_month'); ?>
                                <?php foreach ($block->getCcBlock()->getCcMonths() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="field no-label year">
                        <div class="control">
                            <?php $_ccExpYear = $block->getCard()->getAdditional('cc_exp_year'); ?>
                            <select id="<?php echo $code ?>_expiration_yr" name="payment[cc_exp_year]" class="select year" data-validate='{required:true}'>
                                <?php foreach ($block->getCcBlock()->getCcYears() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php if ($block->getMethod()->getConfigData('useccv')): ?>
            <div class="field cvv required" id="<?php echo $code ?>_cc_type_cvv_div">
                <label for="<?php echo $code ?>_cc_cid" class="label"><span><?php echo __('CCV') ?></span></label>
                <div class="control">
                    <input type="number" title="<?php echo __('Card Verification Number') ?>" class="input-text cvv" id="<?php echo $code ?>_cc_cid" name="payment[cc_cid]" value="" data-validate='{"required-number":true, "validate-cc-cvn":"#<?php echo $code ?>_cc_type"}' autocomplete="off" />
                    <?php $_content = '<img src=\"' . $block->getViewFileUrl('Magento_Checkout::cvv.png') . '\" alt=\"' . __('Card Verification Number Visual Reference') . '\" title=\"' . __('Card Verification Number Visual Reference') . '\" />'; ?>
                    <div class="note">
                        <a href="#" class="action cvv" title="<?php echo __('What is this?') ?>" data-mage-init='{"tooltip": {"content": "<?php echo $_content ?>"}}'><span><?php echo __('What is this?') ?></span></a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php echo __('Save') ?>">
                <span><?php echo __('Save') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo __('Cancel') ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php echo $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?php echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
