<?php
/** @var \Magento\Framework\View\Element\Template $block */
// @codingStandardsIgnoreFile
?>
<div class="block">
    <div class="block-content">
        <div class="box">
            <?= $block->getChildHtml('tokenbase_customer_method_left'); ?>
        </div>
        <div class="box">
            <?= $block->getChildHtml('tokenbase_customer_method_right'); ?>
        </div>
    </div>
</div>
