<?php
/** @var \ParadoxLabs\TokenBase\Block\Customer\Wrapper $block */
?>
<?php if (count($block->getActiveMethods()) > 1): ?>
    <ul class="links">
        <?php foreach ($block->getActiveMethods() as $method): ?>
            <li <?php if ($block->getCurrentMethod() == $method): ?>class="active"<?php endif; ?>>
                <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/*', ['method' => $method])); ?>">
                    <?= $escaper->escapeHtml($block->getMethodTitle($method)); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="manage-payment-method">
    <?= /* @noEscape */ $block->getChildHtml(); ?>
</div>
