<?php
/** @var \ParadoxLabs\TokenBase\Block\Adminhtml\Customer\Cards $block */
?>
<ul class="address-list ui-tabs-nav">
    <?php $cards = $block->getCards(); ?>
    <?php if (!empty($cards)): ?>
        <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
        <?php $currentCardId = $block->getCurrentCard() ? $block->getCurrentCard()->getId() : null; ?>
        <?php foreach ($cards as $card): ?>
            <?php $card = $card->getTypeInstance(); ?>
            <li class="address-list-item<?php if ($card->getExpires() != '' && strtotime((string)$card->getExpires()) < time()): ?> expired<?php endif; ?><?php if ($card->getId() == $currentCardId): ?> ui-state-active<?php endif; ?>">
                <div class="address-list-item-actions">
                    <?php if ($card->isInUse()): ?>
                        <abbr title="<?= $escaper->escapeHtmlAttr(__('This payment record cannot be modified while associated with pending orders.')); ?>"><?= $escaper->escapeHtml(__('Card In Use')); ?></abbr>
                    <?php else: ?>
                        <a class="action-edit" href="<?= $escaper->escapeUrl($block->getUrl('*/*/*', ['_secure' => true, 'id' => $block->getRequest()->getParam('id'), 'form_key' => $block->getFormKey(), 'method' => $card->getMethod(), 'card_id' => $card->getHash()])) ?>"><span><?= $escaper->escapeHtml(__('Edit')) ?></span></a>
                        <a class="action-delete" href="<?= $escaper->escapeUrl($block->getUrl('*/*/paymentinfoDelete', ['_secure' => true, 'id' => $block->getRequest()->getParam('id'), 'form_key' => $block->getFormKey(), 'method' => $card->getMethod(), 'card_id' => $card->getHash()])) ?>"><span><?= $escaper->escapeHtml(__('Delete')) ?></span></a>
                    <?php endif; ?>
                </div>
                <address>
                    <?php if (!empty($card->getType())): ?>
                        <img class="credit-card-type payment-icon" src="<?= $escaper->escapeUrl($block->getViewFileUrl('Magento_Payment::images/cc/' . strtolower((string)$card->getType()) . '.png')); ?>" alt="<?= $escaper->escapeHtmlAttr($block->getCcTypeLabel($card)); ?>" />
                    <?php endif; ?>
                    <span><?= $escaper->escapeHtml($card->getLabel(empty($card->getType()))); ?></span>
                    <?php if (strtotime((string)$card->getExpires()) > time()): ?>
                        <small><?= $escaper->escapeHtml(__('(Expires %1)', date('m/Y', (int)strtotime((string)$card->getExpires())))); ?></small>
                    <?php endif; ?><br>

                    <?= /* @noEscape */ $block->getFormattedCardAddress($card->getAddressObject()); ?>
                </address>
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li><?= $escaper->escapeHtml(__('The customer does not have any payment data saved yet.')) ?></li>
    <?php endif; ?>
</ul>
