<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="ui-tabs">
    <?= /* @noEscape */ $block->getChildHtml('tokenbase_customer_method_left'); ?>
    <div class="address-item-edit">
        <div class="address-item-edit-content">
            <?= /* @noEscape */ $block->getChildHtml('tokenbase_customer_method_right'); ?>
        </div>
    </div>
</div>
