<?php
/** @var \ParadoxLabs\TokenBase\Block\Adminhtml\Customer\Wrapper $block */
// @codingStandardsIgnoreFile
?>
<div class="admin__fieldset-wrapper" id="tokenbase-wrapper" data-mage-init='{"tokenbasePaymentinfo":{}}'>
    <div class="admin__fieldset-wrapper-title">
        <?php $activeMethods = $block->getActiveMethods(); ?>
        <?php if (count($activeMethods) > 1): ?>
            <div class="ui-tabs ui-widget">
                <ul class="ui-tabs-nav tabs-horiz">
                    <?php foreach ($activeMethods as $method): ?>
                        <li class="ui-state-default <?php if ($block->getCurrentMethod() == $method): ?>ui-state-active<?php endif; ?>">
                            <a href="<?= $block->escapeUrl($block->getUrl('*/*/paymentinfo', [ 'method' => $method, 'id' => $block->getRequest()->getParam('id'), 'form_key' => $block->getFormKey() ])); ?>" class="ui-tabs-anchor">
                                <?= $block->escapeHtml($block->getMethodTitle($method)); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    </div>
    <div class="admin__fieldset-wrapper-content">
        <div class="manage-payment-method">
            <?php if (!empty($activeMethods)): ?>
                <?= $block->getChildHtml(); ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('There are currently no active TokenBase payment methods.')); ?>
            <?php endif; ?>
        </div>
    </div>
</div>
