<?php
/** @var \ParadoxLabs\TokenBase\Block\Form\Cc $block */
// @codingStandardsIgnoreFile

$code           = $block->getMethodCode();
$image          = $block->getBrandingImage();
$storedCards    = $block->getStoredCards();
$useVault       = $block->haveStoredCards();
$formData       = [
    "useVault"  => $useVault,
    "code"      => $code,
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<input id="<?php echo $code ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $code ?>" />
<div id="payment_form_<?php echo $code ?>" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"<?php echo $code; ?>FormCc":<?php echo $serializedFormData ?>}'>
    <fieldset class="admin__fieldset">
        <?php if ($image): ?>
            <div class="page-actions">
                <img src="<?php echo $image; ?>" />
            </div>
        <?php endif; ?>
        <?php if ($storedCards): ?>
            <div class="admin__field" id="<?php echo $code ?>_card_selector">
                <div class="admin__field-control control">
                    <select id="<?php echo $code ?>_card_id" name="payment[card_id]" class="select admin__control-select">
                        <?php /** @var \ParadoxLabs\TokenBase\Model\Card $card */ ?>
                        <?php foreach ($storedCards as $card): ?>
                            <?php $card = $card->getTypeInstance(); ?>
                            <option value="<?php echo $card->getHash() ?>" <?php if ($card->getId() == $block->getInfoData('tokenbase_id') || count($storedCards) == 1): ?>selected="selected"<?php endif; ?>>
                                <?php echo $card->getLabel() ?>
                            </option>
                        <?php endforeach; ?>
                        <option value='' <?php if (count($storedCards) > 1 && $block->getInfoData('tokenbase_id') == ''): ?>selected="selected"<?php endif; ?>><?php echo __('Add new card') ?></option>
                    </select>
                </div>
            </div>
        <?php endif; ?>
        <div class="admin__field hide_if_card_selected">
            <label class="label admin__field-label" for="<?php echo $code ?>_cc_type" ><?php echo __('Credit Card Type') ?><span class="required">*</span></label>
            <div class="admin__field-control control">
                <select id="<?php echo $code ?>_cc_type" name="payment[cc_type]" class="required-entry _required select admin__control-select validate-cc-type-select">
                    <option value="">--<?php echo __('Please Select')?>--</option>
                    <?php $_ccType = $block->getInfoData('cc_type') ?>
                    <?php foreach ($block->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="admin__field hide_if_card_selected">
            <label class="label admin__field-label" for="<?php echo $code ?>_cc_number"><?php echo __('Credit Card Number') ?><span class="required">*</span></label>
            <div class="admin__field-control control">
                <input type="text" id="<?php echo $code ?>_cc_number" name="payment[cc_number]"  title="<?php echo __('Credit Card Number') ?>" class="input-text admin__control-text validate-cc-number validate-cc-type" value="<?php echo $block->getInfoData('cc_number'); ?>" autocomplete="off" />
            </div>
        </div>
        <div id="<?php echo $code ?>_cc_type_exp_div" class="admin__field hide_if_card_selected">
            <label class="label admin__field-label" for="<?php echo $code ?>_expiration" ><?php echo __('Expiration Date') ?><span class="required">*</span></label>
            <div class="admin__field-control control">
                <select id="<?php echo $code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry _required select admin__control-select">
                    <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
                    <?php foreach ($block->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if ($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry _required select admin__control-select">
                    <?php foreach ($block->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if ($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <?php echo $block->getChildHtml() ?>
        <?php if ($block->hasVerification()): ?>
            <div id="<?php echo $code ?>_cc_cid_div" class="admin__field <?php if ($block->getMethod()->getConfigData('require_ccv') == 0): ?>hide_if_card_selected<?php endif; ?>">
                <label class="label admin__field-label" for="<?php echo $code ?>_cc_cid" ><?php echo __('Card Verification Number') ?><span class="required">*</span></label>
                <div class="admin__field-control control">
                    <div class="v-fix">
                        <input type="text" title="<?php echo __('Card Verification Number') ?>" class="input-text admin__control-text cvv required-entry validate-cc-cvn" id="<?php echo $code ?>_cc_cid" name="payment[cc_cid]" value="<?php echo $block->getInfoData('cc_cid'); ?>" autocomplete="off" />
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <?php if (!$block->isGuestCheckout()): ?>
            <div id="<?php echo $code ?>_save_div" class="admin__field hide_if_card_selected">
                <div class="admin__field-control control">
                    <?php if ($block->getMethod()->getConfigData('allow_unsaved')): ?>
                        <input type="hidden" name="payment[save]" value="0" />
                        <input type="checkbox" title="<?php echo __('Save for next time') ?>" class="input-checkbox" id="<?php echo $code ?>_save" name="payment[save]" value="1" <?php if ($block->getInfoData('save') !== 0): ?>checked="checked"<?php endif; ?> />
                        <label for="<?php echo $code ?>_save"><?php echo __('Save for next time') ?></label>
                    <?php else: ?>
                        <input type="hidden" name="payment[save]" value="1" />
                        <label class="label admin__field-label" for="<?php echo $code ?>_save"><?php echo __('For your convenience, this data will be stored securely by our payment processor.') ?></label>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </fieldset>
</div>
