<?php
/** @var \ParadoxLabs\TokenBase\Block\Adminhtml\Customer\Form $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php $code = $escaper->escapeHtmlAttr($block->getCode()); ?>

<div class="block-title">
    <h2>
        <?php if ($block->isEdit()): ?>
            <?= $escaper->escapeHtml(__('Editing %1', $block->getCard()->getLabel())); ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('Add A Bank Account (eCheck)')); ?>
        <?php endif; ?>
    </h2>
</div>

<form action="<?= $escaper->escapeHtmlAttr($block->getAction()); ?>" method="post" id="<?= /* @noEscape */ $code; ?>-form-validate" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <input type="hidden" name="card_id" value="<?= $block->getCard()->getId() ? $escaper->escapeHtmlAttr($block->getCard()->getHash()) : ''; ?>" />
    <input type="hidden" name="method" value="<?= /* @noEscape */ $code; ?>" />
    <fieldset class="admin__fieldset">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $escaper->escapeHtml(__('Cardholder Information')) ?></span>
            </strong>
        </div>
        <div class="admin__field field-name-firstname _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-firstname"><span><?= $escaper->escapeHtml(__('First Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[firstname]" id="<?= /* @noEscape */ $code; ?>-firstname" title="<?= $escaper->escapeHtmlAttr(__('First Name')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getFirstname()) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('firstname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field field-name-lastname _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-lastname"><span><?= $escaper->escapeHtml(__('Last Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[lastname]" id="<?= /* @noEscape */ $code; ?>-lastname" title="<?= $escaper->escapeHtmlAttr(__('Last Name')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getLastname()) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('lastname')) ?>" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field company">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-company"><span><?= $escaper->escapeHtml(__('Company')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[company]" id="<?= /* @noEscape */ $code; ?>-company" title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCompany()) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>">
            </div>
        </div>
        <?php $phoneValidation = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone'); ?>
        <div class="admin__field telephone<?php if (strpos($phoneValidation, 'required') !== false): ?> _required<?php endif; ?>">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-telephone"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[telephone]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($phoneValidation) ?>" id="<?= /* @noEscape */ $code; ?>-telephone" data-validate='{required:true}'>
            </div>
        </div>
    </fieldset>
    <fieldset class="admin__fieldset">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $escaper->escapeHtml(__('Cardholder Address')) ?></span>
            </strong>
        </div>
        <?php $_streetValidationClass = $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
        <div class="admin__field street _required">
            <label for="<?= /* @noEscape */ $code; ?>-street" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Street')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address')) ?>" id="<?= /* @noEscape */ $code; ?>-street" class="admin__control-text <?= /* @noEscape */ $_streetValidationClass ?>" data-validate='{required:true}' />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++): ?>
                        <?php $lineNo = (int)($_i + 1); ?>
                        <div class="admin__field additional">
                            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-street_<?= /* @noEscape */ $lineNo; ?>">
                                <span><?= $escaper->escapeHtml(__('Street Address %1', $lineNo)); ?></span>
                            </label>
                            <div class="admin__field-control">
                                <input type="text" name="billing[street][]" value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($lineNo)) ?>" title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $lineNo)) ?>" id="<?= /* @noEscape */ $code; ?>-street_<?= /* @noEscape */ $lineNo ?>" class="admin__control-text <?= /* @noEscape */ $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
        <div class="admin__field city _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-city"><span><?= $escaper->escapeHtml(__('City')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[city]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>" title="<?= $escaper->escapeHtmlAttr(__('City')) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="<?= /* @noEscape */ $code; ?>-city" data-validate='{required:true}'>
            </div>
        </div>
        <div class="admin__field region _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-region-id"><span><?= $escaper->escapeHtml(__('State/Province')) ?></span></label>
            <div class="admin__field-control">
                <select id="<?= /* @noEscape */ $code; ?>-region-id" name="billing[region_id]" title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-select validate-select" <?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>>
                    <option value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="<?= /* @noEscape */ $code; ?>-region" name="billing[region]" value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"  title="<?= $escaper->escapeHtmlAttr(__('State/Province')) ?>" class="admin__control-text <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?=(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="admin__field zip _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-zip"><span><?= $escaper->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" name="billing[postcode]" value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>" title="<?= $escaper->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="<?= /* @noEscape */ $code; ?>-zip" class="admin__control-text validate-zip-international <?= $escaper->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
            </div>
        </div>
        <div class="admin__field country _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code; ?>-country"><span><?= $escaper->escapeHtml(__('Country')) ?></span></label>
            <div class="admin__field-control">
                <?= /* @noEscape */ str_replace('class="', 'class="admin__control-select ', $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'billing[country_id]', $code . '-country')) ?>
            </div>
        </div>
    </fieldset>
    <fieldset class="admin__fieldset payment items ccard <?= /* @noEscape */ $code ?>">
        <div class="admin__fieldset-wrapper-title">
            <strong class="title">
                <span><?= $escaper->escapeHtml(__('Bank Information')) ?></span>
            </strong>
        </div>
        <div class="admin__field name _required">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-name" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Name on Account')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-account-name" name="payment[echeck_account_name]"
                       title="<?= $escaper->escapeHtmlAttr(__('Name on Account')) ?>" class="admin__control-text" maxlength="22"
                       value="<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_account_name')); ?>"
                       data-validate='{required:true}' />
            </div>
        </div>
        <div class="admin__field name _required">
            <label for="<?= /* @noEscape */ $code ?>-echeck-bank-name" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Bank Name')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-bank-name" name="payment[echeck_bank_name]"
                       title="<?= $escaper->escapeHtmlAttr(__('Bank Name')) ?>" class="admin__control-text" maxlength="50" autocomplete="off"
                       value="<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_bank_name')); ?>"
                       data-validate='{required:true}' />
            </div>
        </div>
        <div class="admin__field number _required">
            <label for="<?= /* @noEscape */ $code ?>-echeck-routing-number" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Routing Number')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-routing-number" name="payment[echeck_routing_no]"
                       title="<?= $escaper->escapeHtmlAttr(__('Routing Number')) ?>" class="admin__control-text minimum-length-9" maxlength="9"
                       value="<?php if ($block->getCard()->getId() && $block->getCard()->getAdditional('echeck_routing_number_last4') != ''): ?>XXXX<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_routing_number_last4')); ?><?php endif; ?>" autocomplete="off"
                       data-validate='{"required-number":true,"validate-length":true}' />
            </div>
        </div>
        <div class="admin__field number _required">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-number" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Account Number')) ?></span></label>
            <div class="admin__field-control _with-tooltip">
                <input type="text" id="<?= /* @noEscape */ $code ?>-echeck-account-number" name="payment[echeck_account_no]"
                       title="<?= $escaper->escapeHtmlAttr(__('Account Number')) ?>" class="admin__control-text minimum-length-5 maximum-length-17"
                       value="<?php if ($block->getCard()->getId() && $block->getCard()->getAdditional('echeck_account_number_last4') != ''): ?>XXXX<?= $escaper->escapeHtmlAttr($block->getCard()->getAdditional('echeck_account_number_last4')); ?><?php endif; ?>" maxlength="17"
                       data-validate='{"required-number":true,"validate-length":true}' autocomplete="off" />
                <div class="admin__field-tooltip tooltip">
                    <span class="admin__field-tooltip-action action-help" tabindex="0" data-toggle="dropdown">
                        <span><?= $escaper->escapeHtml(__('Where do I find these numbers?')) ?></span>
                    </span>
                    <div class="admin__field-tooltip-content" data-target="dropdown" aria-hidden="true">
                        <p><?= $escaper->escapeHtml(__('On the bottom of your checks, you will see three groups of numbers. Usually the first one is your routing number, and the second is your account number.')) ?></p>
                        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('ParadoxLabs_TokenBase::images/ach.png')) ?>" alt="<?= $escaper->escapeHtmlAttr(__('Visual reference for locating routing number and account number on a check')) ?>" />
                    </div>
                </div>
            </div>
        </div>
        <div class="admin__field type _required">
            <label for="<?= /* @noEscape */ $code ?>-echeck-account-type-checking" class="admin__field-label"><span><?= $escaper->escapeHtml(__('Account Type')) ?></span></label>
            <div class="admin__field-control">
                <?php $typeValue = $block->getCard()->getAdditional('echeck_account_type') ?: 'checking'; ?>
                <?php foreach ($block->getHelper()->getAchAccountTypes() as $k => $v): ?>
                    <div>
                        <input type="radio" name="payment[echeck_account_type]"
                               id="<?= /* @noEscape */ $code ?>-echeck-account-type-<?= $escaper->escapeHtmlAttr($k); ?>"
                               value="<?= $escaper->escapeHtmlAttr($k); ?>" <?php if ($k == $typeValue): ?>checked="checked"<?php endif ?>
                               data-validate='{"validate-one-required-by-name":true}' />
                        <label for="<?= /* @noEscape */ $code ?>-echeck-account-type-<?= $escaper->escapeHtmlAttr($k); ?>"><?= $escaper->escapeHtml($v); ?></label>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action-save primary" data-action="save-address" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action-back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"><span><?= $escaper->escapeHtml(__('Cancel')) ?></span></a>
        </div>
    </div>
</form>
<?php $regionId = (int)$block->getRegionId() ?>
<?php /* @see Magento\Customer\Block\Adminhtml\Edit\Renderer\Region::render() */ ?>
<?php $inlineScript = <<<JS
    require(["prototype", "mage/adminhtml/form"], function(){
        jQuery("#{$code}-region-id").attr("defaultValue", "{$regionId}");
        new RegionUpdater("{$code}-country", "{$code}-region", "{$code}-region-id", {$this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson()} );
    });

    require(["jquery"], function() {
        /** This is necessary for parsing of mage-data-init elements in the AJAX requests */
        jQuery('#{$code}-form-validate').trigger('contentUpdated');
    });
JS;
?>
<?php if (isset($secureRenderer) && $secureRenderer instanceof \Magento\Framework\View\Helper\SecureHtmlRenderer): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $inlineScript, false) ?>
<?php else: ?>
    <script><?= /* @noEscape */ $inlineScript ?></script>
<?php endif; ?>
